language: php

matrix:
  fast_finish: true
  allow_failures:
    - php:
      - hhvm
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
      dist: trusty

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

script: phpunit
