language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

script: phpunit
