language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

script: vendor/bin/phpunit
