language: php
os: linux
dist: xenial

jobs:
  fast_finish: true
  include:
    - php: 7.2
      env: VERSIONS=--prefer-lowest
    - php: 7.3
    - php: 7.4

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction
  - travis_retry composer update --root-reqs $VERSIONS

script: vendor/bin/phpunit
